#-----------------------------------------
# Basic Deploy
#-----------------------------------------
name: Basic Deploy
env:
  APP_NAME: APPHP MVC FRAMEWORK
  DEPLOY_PACKAGE_NAME: "apphp-deploy-${{ github.sha }}"

#  [push]   
on:
  push:
    branches: 
      - master

jobs:
  my-testing:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo  
      uses: actions/checkout@v1
    
    - name: List current folder
      run: ls -la

    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    
    - name: Print env variables
      run: | 
        echo "App Name: ${{ env.APP_NAME }}"
        echo "Pack Name: ${{ env.DEPLOY_PACKAGE_NAME }}"
    
    - name: Test some packages
      run: aws --version
      
    
      
        
      
