#-----------------------------------------
# Framework Deploy
#-----------------------------------------
name: Framework Deploy
env:
  APP_NAME: APPHP MVC FRAMEWORK
  DEPLOY_PACKAGE_NAME: "apphp-deploy-${{ github.sha }}"

# Run on [push]
on:
  push:
    branches: 
      #- master
      - dev

jobs:
#  testing:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Run testing
#      run: echo Testing is running...
#    
#    - name: Print env variables
#      run: | 
#        echo "App Name: ${{ env.APP_NAME }}"
   

  deploy:
    runs-on: ubuntu-latest
 #   needs: [testing]
    
    steps:
      - name: Print env variables
        run: | 
          echo "Pack Name: ${{ env.DEPLOY_PACKAGE_NAME }}"
          
      - name: Git clone my repo  
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la
    
      - name: Check some packages if they are installed
        run: | 
          composer --version
          phpunit --version

      - name: Runt PHPUnit tests
        run: composer tests

