#-----------------------------------------
# Basic Deploy
#-----------------------------------------
name: Basic Deploy
env:
  APP_NAME: APPHP MVC FRAMEWORK
  DEPLOY_PACKAGE_NAME: "apphp-deploy-${{ github.sha }}"

#  [push]   
on:
  push:
    branches: 
      #- master
      - dev

jobs:
#  my-testing:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Run testing
#      run: echo Testing is running...
#    
#    - name: Print env variables
#      run: | 
#        echo "App Name: ${{ env.APP_NAME }}"
   

  my-deploy:
    runs-on: ubuntu-latest
 #   needs: [my-testing]
    
    steps:
      - name: Print env variables
        run: | 
          echo "Pack Name: ${{ env.DEPLOY_PACKAGE_NAME }}"
          
      - name: Git clone my repo  
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la
    
      - name: Check some packages if they are installed
        run: | 
          composer --version
          phpunit --version

       - name: Install Composer
        run: |
          apt-get update && apt-get install -y unzip
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer install

       - name: Install PHPUnit
        run: composer require phpunit/phpunit ^7

      - name: Check again some packages if they are installed
        run: | 
          composer --version
          phpunit --version
    
      - name: Runt PHPUnit tests 
        run: composer tests

