#-----------------------------------------
# Framework Deploy
#-----------------------------------------
name: build
env:
  APP_NAME: ApPHP MVC Framework
  DEPLOY_PACKAGE_NAME: "apphp-deploy-${{ github.sha }}"

# Run on [push]
on:
  push:
    branches: 
      - master
      #- dev

jobs:
#  my-testing:
#    runs-on: ubuntu-latest
#    env:
#      VAR1: "Local var1"
#      VAR2: "Local var2"
#    steps:
#    - name: Run testing
#      run: echo Testing is running...
#    - name: Print env variables
#      run: |
#        echo "App Name: ${{ env.APP_NAME }}"
#    - name: Print local env variables
#      run: |
#        echo "Var1: ${{ env.VAR1 }}"
#        echo "Var2: ${{ env.VAR2 }}"
#        echo "Var2: $LOCAL_VAR"
#      env:
#        LOCAL_VAR: "Super local var"
   

  deploy:
    runs-on: ubuntu-latest
 #   needs: [testing]
    
    steps:
      - name: Print env variables
        run: | 
          echo "Pack Name: ${{ env.DEPLOY_PACKAGE_NAME }}"

      - name: Git clone my repo  
        uses: actions/checkout@v1

      - name: List current folder
        run: ls -la
    
      - name: Check some packages if they are installed
        run: | 
          composer --version
          php --version
          phpunit --version

      - name: Install required packages
        run: composer update

#      - name: Install PHPUnit
#        run: composer require phpunit/phpunit ^7.5

#      - name: Check again some packages if they are installed
#        run: |
#          composer --version
#          phpunit --version

      - name: Runt PHPUnit tests for the Framework
        run: composer tests






